In [1]:
import pandas as pd

df = pd.read_csv("../data/e1_nutrients.csv")
df.head()

   Depth  NITRITE  NITRATE+NITRITE  AMMONIA  SILICATE  PHOSPHATE
0      0     0.03             0.38     0.00      1.27       0.06
1     10     0.03             0.45     0.98      1.14       0.06
2     20     0.23             2.08     1.10      2.54       0.27
3     30     0.04             0.39     0.00      1.15       0.08
4     40     0.28             2.19     1.11      2.59       0.19

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2496 entries, 0 to 2495
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Depth            2496 non-null   int64
 1   NITRITE          2496 non-null   float64
 2   NITRATE+NITRITE  2496 non-null   float64
 3   AMMONIA          2496 non-null   float64
 4   SILICATE         2496 non-null   float64
 5   PHOSPHATE        2496 non-null   float64
dtypes: float64(5), int64(1)
memory usage: 117.1 KB

In [3]:
df.describe()

,Depth,NITRITE,NITRATE+NITRITE,AMMONIA,SILICATE,PHOSPHATE
count,2496.000000,2496.000000,2496.000000,2496.000000,2496.000000,2496.000000
mean,26.919071,0.210601,2.905465,0.519247,1.939455,0.290741
std,19.729713,0.328292,2.260390,0.654011,1.076337,0.175216
min,0.000000,0.000000,0.000000,0.000000,0.040000,0.000000
25%,10.000000,0.040000,0.430000,0.100000,1.010000,0.160000
50%,30.000000,0.110000,3.030000,0.240000,2.080000,0.300000
75%,40.000000,0.230000,4.972500,0.640000,2.750000,0.410000
max,60.000000,2.900000,8.350000,4.170000,8.820000,2.560000

In [4]:
df.isna().sum()

Depth              0
NITRITE            0
NITRATE+NITRITE    0
AMMONIA            0
SILICATE           0
PHOSPHATE          0
dtype: int64